In [13]:
#IMPORTING PANDAS AND NUMPY LIBRARY
import pandas as pd
import numpy as np

In [14]:
#FETCHING THE CSV FILE
df=pd.read_csv('customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [15]:
#FETCHING INFORMATION ABOUT COLUMN NAME
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [16]:
#FETCHING HOW MANY NULL VALUES ARE THERE
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [17]:
#FILLING NA VALUES WITH MEDIAN VALUES
df['Review Rating']=df.groupby('Category')['Review Rating'].transform (lambda a:a.fillna(a.median()))
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [18]:
#REPLACING SPACES WITH _
df.columns=df.columns.str.replace(' ','_')
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount_(USD)', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Discount_Applied', 'Promo_Code_Used', 'Previous_Purchases',
       'Payment_Method', 'Frequency_of_Purchases'],
      dtype='object')

In [19]:
#CREATING A COLUMN age_group
labels=['Young Adult','Adult','Middle-aged','Senior']
df['Age_group']=pd.qcut(df['Age'],q=4,labels=labels)

In [20]:
df[['Age','Age_group']].head()

   Age    Age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged

In [21]:

#creating a column frequency of purchases
df['Frequency_of_Purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [22]:
f_m ={'Fortnightly': 14, 'Weekly': 7, 'Annually': 365, 'Quarterly': 90, 'Bi -weekly': 14}
df['Frequency_of_Purchases_days'] = df['Frequency_of_Purchases'].map(f_m)
df

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount_(USD),Location,Size,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment_Method,Frequency_of_Purchases,Age_group,Frequency_of_Purchases_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-aged,365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly,Adult,7.0
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,Middle-aged,NaN
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly,Middle-aged,90.0
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly,Adult,7.0
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly,Middle-aged,90.0

In [23]:
(df['Promo_Code_Used']==df['Discount_Applied']).all()

True

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer_ID                  3900 non-null   int64
 1   Age                          3900 non-null   int64
 2   Gender                       3900 non-null   object
 3   Item_Purchased               3900 non-null   object
 4   Category                     3900 non-null   object
 5   Purchase_Amount_(USD)        3900 non-null   int64
 6   Location                     3900 non-null   object
 7   Size                         3900 non-null   object
 8   Color                        3900 non-null   object
 9   Season                       3900 non-null   object
 10  Review_Rating                3900 non-null   float64
 11  Subscription_Status          3900 non-null   object
 12  Shipping_Type                3900 non-null   object
 13  Discount_Applied             3900 non-null   object
 14  Promo_Code_Used              3900 non-null   object
 15  Previous_Purchases           3900 non-null   int64
 16  Payment_Method               3900 non-null   object
 17  Frequency_of_Purchases       3900 non-null   object
 18  Age_group                    3900 non-null   category
 19  Frequency_of_Purchases_days  2216 non-null   float64
dtypes: category(1), float64(2), int64(4), object(13)
memory usage: 583.0+ KB

In [25]:
#DRPPING promo_code_used COLUMN
df = df.drop('Promo_Code_Used', axis=1)
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount_(USD)', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Discount_Applied', 'Previous_Purchases', 'Payment_Method',
       'Frequency_of_Purchases', 'Age_group', 'Frequency_of_Purchases_days'],
      dtype='object')

In [26]:
df.rename(columns={'Purchase_Amount_(USD)':'Purchase_Amount'},inplace=True)

In [27]:
!python -m pip install mysql-connector-python
import mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in c:\users\amanj\appdata\roaming\python\python311\site-packages (9.6.0)

[notice] A new release of pip is available: 23.3.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:

import mysql.connector

In [29]:
#CONNECTING DATABASE
import mysql.connector

conn = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="tiger@123",
    database="customer_behaviour"
)
print("Connected successfully")

Connected successfully

In [30]:
%pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\users\amanj\appdata\roaming\python\python311\site-packages (2.0.49)
Requirement already satisfied: pymysql in c:\users\amanj\appdata\roaming\python\python311\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\amanj\appdata\roaming\python\python311\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\amanj\appdata\roaming\python\python311\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.3.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:tiger@123@127.0.0.1/customer_behaviour')

print("Engine created successfully")

Engine created successfully

In [32]:
engine = create_engine('mysql+pymysql://root:tiger%40123@127.0.0.1/customer_behaviour')

In [33]:
#update database to mysql
df.to_sql(
    name = "customers",
    con = engine,
    if_exists = "replace",
    index = False
)

3900